// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.3
// Project name: game

#ifndef _GAME_UI_H
#define _GAME_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"
extern lv_obj_t * ui_Screen2;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
void ui_event_Label2(lv_event_t * e);
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Slider2;
extern lv_obj_t * ui_Slider1;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Image2;
void ui_event_button1( lv_event_t * e);
extern lv_obj_t *ui_button1;
void ui_event_button2( lv_event_t * e);
extern lv_obj_t *ui_button2;
void ui_event_restartButton( lv_event_t * e);
extern lv_obj_t *ui_restartButton;
extern lv_obj_t *ui_restartLabel;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_b_png);    // assets\b.png
LV_IMG_DECLARE(ui_img_10259980_png);    // assets\10259980.png
LV_IMG_DECLARE(ui_img_1_png);    // assets\1.png
LV_IMG_DECLARE(ui_img_0_png);    // assets\0.png
LV_IMG_DECLARE(ui_img_13_png);    // assets\13.png
LV_IMG_DECLARE(ui_img_red_png);    // assets\red.png
LV_IMG_DECLARE(ui_img_green_png);    // assets\green.png
LV_IMG_DECLARE(ui_img_ko_png);    // assets\ko.png
LV_IMG_DECLARE(ui_img_11_png);    // assets\11.png
LV_IMG_DECLARE(ui_img_12_png);    // assets\12.png
LV_IMG_DECLARE(ui_img_14_png);    // assets\14.png
LV_IMG_DECLARE(ui_img_15_png);    // assets\15.png
LV_IMG_DECLARE(ui_img_16_png);    // assets\16.png
LV_IMG_DECLARE(ui_img_17_png);    // assets\17.png
LV_IMG_DECLARE(ui_img_18_png);    // assets\18.png
LV_IMG_DECLARE(ui_img_19_png);    // assets\19.png
LV_IMG_DECLARE(ui_img_2_png);    // assets\2.png
LV_IMG_DECLARE(ui_img_20_png);    // assets\20.png
LV_IMG_DECLARE(ui_img_21_png);    // assets\21.png
LV_IMG_DECLARE(ui_img_3_png);    // assets\3.png
LV_IMG_DECLARE(ui_img_4_png);    // assets\4.png
LV_IMG_DECLARE(ui_img_5_png);    // assets\5.png
LV_IMG_DECLARE(ui_img_6_png);    // assets\6.png
LV_IMG_DECLARE(ui_img_7_png);    // assets\7.png
LV_IMG_DECLARE(ui_img_8_png);    // assets\8.png
LV_IMG_DECLARE(ui_img_9_png);    // assets\9.png




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
