// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.3
// Project name: game

#ifndef _GAME_UI_COMP_H
#define _GAME_UI_COMP_H

#ifdef __cplusplus
extern "C" {
#endif


lv_obj_t * ui_comp_get_child(lv_obj_t * comp, uint32_t child_idx);
extern uint32_t LV_EVENT_GET_COMP_CHILD;

// COMPONENT Button2
#define UI_COMP_BUTTON2_BUTTON2 0
#define _UI_COMP_BUTTON2_NUM 1
lv_obj_t * ui_Button2_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
